### ISSUE TITLE
Unknown register name 'lr'.

### ISSUE THREAD

**Issue by jkrupp** [alexandrebelloni/whoosh#2]
Awesome work!  Thanks for sharing!  
I'd like to see it first hand, but I'm having trouble even building it.  Any ideas? Error message below:

me@me-Inspiron-1090:~/whoosh$ make imx6_sabrelite_config
me@me-Inspiron-1090:~/whoosh$ make 
gcc -c -g -Os -nostartfiles -nostdlib main.c -o main.o
main.c:68:1: warning: ‘naked’ attribute directive ignored [-Wattributes]
main.c:73:1: warning: ‘naked’ attribute directive ignored [-Wattributes]
main.c: In function ‘start’:
main.c:98:2: error: unknown register name ‘lr’ in ‘asm’
make: **\* [main.o] Error 1
me@me-Inspiron-1090:~/whoosh$

**Comment by alexandrebelloni** [comment]
It seems that you are trying to compil whoosh with your x86 compiler. Please define CROSS_COMPILE correctly.
